apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: persistent
  labels:
    db: example
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /db/data
