apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: persistent
  labels:
    db: example
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
