apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: exposed-dep1
  name: exposed-dep1
  namespace: exposing
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30010
  selector:
    app: exposed-dep1
  type: NodePort
status:
  loadBalancer: {}
