apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: primary
  name: primary
  namespace: canary
spec:
  replicas: 4
  selector:
    matchLabels:
      version: v1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        version: v1
        app: frontend
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
