apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    version: v2
  name: secondary
  namespace: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      version: v2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        version: v2
        app: frontend
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
