apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: primary
  name: primary
  namespace: canary
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30120
  selector:
    app: frontend
  type: NodePort
status:
  loadBalancer: {}
