apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: printer
  namespace: jobs-cronjobs
spec:
  backoffLimit: 4
  completions: 10
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: registry.k8s.io/busybox
        name: printer
        command: ["echo", "I'm a printer machine"]
        resources: {}
      restartPolicy: Never
status: {}
