apiVersion: v1
kind: Pod
metadata:
  namespace: secret
  creationTimestamp: null
  labels:
    run: secret2
  name: secret2
spec:
  containers:
    - image: httpd:alpine
      name: secret2
      resources: {}
      envFrom:
        - secretRef:
            name: auth
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
