apiVersion: v1
kind: Pod
metadata:
  namespace: secret
  creationTimestamp: null
  labels:
    run: secret1
  name: secret1
spec:
  containers:
  - image: httpd:alpine
    name: secret1
    resources: {}
    env:
      - name: "USER"
        valueFrom:
          secretKeyRef:
            key: user
            name: auth
      - name: "PASSWORD"
        valueFrom:
          secretKeyRef:
            key: password
            name: auth
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
