apiVersion: v1
kind: Pod
metadata:
  namespace: secret
  creationTimestamp: null
  labels:
    run: secret3
  name: secret3
spec:
  volumes:
    - name: users
      secret:
        secretName: users
  containers:
  - image: httpd:alpine
    name: secret3
    volumeMounts:
      - mountPath: /users
        name: users
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
