apiVersion: v1
kind: Pod
metadata:
  namespace: "readiness-liveness"
  name: liveness-pod
spec:
  containers:
    - name: liveness-pod
      image: registry.k8s.io/busybox
      args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5